server:
  port: ${PORT:8080}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

# --- JACKSON ----
spring.jackson:
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
    FAIL_ON_EMPTY_BEANS: false
  deserialization:
    FAIL_ON_UNKNOWN_PROPERTIES: false
  parser:
    ALLOW_COMMENTS: true
    ALLOW_UNQUOTED_FIELD_NAMES: true
    ALLOW_SINGLE_QUOTES: true